# Generated by Django 5.1.7 on 2025-03-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_organizationprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationprofile',
            options={'verbose_name': 'Organization Profile', 'verbose_name_plural': 'Organization Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
