# Generated by Django 5.1.7 on 2025-03-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_organizationprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='organization_profiles/'),
        ),
    ]
