# Generated by Django 5.1.7 on 2025-03-31 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_organizationprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationprofile',
            name='profile_picture',
        ),
    ]
