# Generated by Django 5.1.7 on 2025-03-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_organizationprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
