# Generated by Django 5.1.7 on 2025-04-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_event_date_alter_event_title_postevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='postevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
