# Generated by Django 5.1.7 on 2025-04-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_postevent_image_alter_postevent_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationprofile',
            options={'verbose_name': 'Organization_Profile', 'verbose_name_plural': 'Organization_Profiles'},
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='organization_profiles/'),
        ),
    ]
