# Generated by Django 5.2 on 2025-05-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_organizationprofile_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
